### ISSUE TITLE
Difficulty with exporting torch -> caffe2 model conversion: RuntimeError: Only tuples, lists and Variables are supported as JIT inputs/outputs

### ISSUE THREAD

**Issue by karl-mccarron** [zetyquickly/DensePoseFnL#18]
Hi,

First, I should say thanks for doing this great work!

I'm looking into this now and have been having trouble with exporting the model to a format for caffe2, as outlined in the paper (section 4.4).

I have installed the versions of the mentioned requirements, and when using `export_model.py` from the `detectron2` repository, I come across the following error:

```
Traceback (most recent call last):
  File "C:\Users\xxx\deep_learning\android\DensePoseFnL\export_model.py", line 239, in <module>
    exported_model = export_caffe2_tracing(cfg, torch_model, sample_inputs)
  File "C:\Users\xxx\deep_learning\android\DensePoseFnL\export_model.py", line 58, in export_caffe2_tracing
    caffe2_model = tracer.export_caffe2()
  File "c:\users\xxx\deep_learning\android\detectron2\detectron2\export\api.py", line 81, in export_caffe2
    predict_net, init_net = export_caffe2_detection_model(
  File "c:\users\xxx\deep_learning\android\detectron2\detectron2\export\caffe2_export.py", line 146, in export_caffe2_detection_model
    onnx_model = export_onnx_model(model, (tensor_inputs,))
  File "c:\users\xxx\deep_learning\android\detectron2\detectron2\export\caffe2_export.py", line 56, in export_onnx_model
    torch.onnx.export(
  File "C:\Users\xxx\miniconda3\lib\site-packages\torch\onnx\__init__.py", line 316, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "C:\Users\xxx\miniconda3\lib\site-packages\torch\onnx\utils.py", line 107, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "C:\Users\xxx\miniconda3\lib\site-packages\torch\onnx\utils.py", line 724, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "C:\Users\xxx\miniconda3\lib\site-packages\torch\onnx\utils.py", line 493, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "C:\Users\xxx\miniconda3\lib\site-packages\torch\onnx\utils.py", line 437, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "C:\Users\xxx\miniconda3\lib\site-packages\torch\onnx\utils.py", line 388, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "C:\Users\xxx\miniconda3\lib\site-packages\torch\jit\_trace.py", line 1166, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "C:\Users\xxx\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\xxx\miniconda3\lib\site-packages\torch\jit\_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "C:\Users\xxx\miniconda3\lib\site-packages\torch\jit\_trace.py", line 121, in wrapper
    out_vars, _ = _flatten(outs)
RuntimeError: Only tuples, lists and Variables are supported as JIT inputs/outputs. Dictionaries and strings are also accepted, but their usage is not recommended. Here, received an input of unsupported type: DensePoseChartPredictorOutputWithConfidences
```

I get a similar error with all 3 of the models referenced in the project, sadly (albeit with a different type mentioned if the CSE model is used).

Is there a script you're using to convert this, or is there something I'm missing in this process?

Thanks your your help!

**Comment by zetyquickly** [comment]
Hello,

The script was available on a previous version of the. Please have a look at previous commits.

This also requires a model to be caffe2 exportable, in this version we haven't preserve this feature

**Comment by zetyquickly** [comment]
Regarding the error you see. This issue occurs because the model you are trying to trace returns detectron2 structure and not a list or tuple of torch.Tensors. Rewrite (S,I,U,V) output of DensePose model as a tuple of Tensors, that'll help

**Comment by karl-mccarron** [comment]
If the current version of the repo doesn't have this functionality, I'll have a look through previous commits and see if I can get it working.

I'll also see if I can rewrite the mode output as tuples as well, as that might solve it, thanks!

**Comment by pramishp** [comment]
@zetyquickly , Can you add the previous model which was caffe2 exportable ?

**Comment by zetyquickly** [comment]
the previous weights are out of date because of unknown issue which led to performance degradation. I assume that the current weights still might be exportable, but you need to follow the export scripts from previous version

**Comment by zetyquickly** [comment]
detectron2 export is all you need (c)

https://detectron2.readthedocs.io/en/latest/modules/export.html

**Comment by pramishp** [comment]
I was able to convert the models using detectron but, the inference from both torchscript and onnx model were empty.
``` (tensor([], size=(0, 4), grad_fn=<ReshapeAliasBackward0>), tensor([], dtype=torch.int64), tensor([], grad_fn=<IndexBackward0>), tensor([1067,  800]))```

I am using this commit `git checkout bb96d0b01d0605761ca182d0e3fac6ead8d8df6e` of detectron. 

The model I used is: `mobile_parsing_rcnn_b_wc2m_s3x.pth`.
