### ISSUE TITLE
ModuleNotFoundError: No module named 'geffnet'

### ISSUE THREAD

**Issue by abhaydoke09** [zetyquickly/DensePoseFnL#8]
I installed the detectron2 as mentioned in the readme.
When I am trying to run train_net.py from DensePoseFnL folder, I am getting following error.

Traceback (most recent call last):
  File "train_net.py", line 21, in <module>
    from densepose import DatasetMapper, DensePoseCOCOEvaluator, add_densepose_config
  File "/densepose/detectron2-test/detectron2/projects/DensePoseFnL/densepose/__init__.py", line 8, in <module>
    from .modeling.geffnet_backbone import *
  File "/densepose/detectron2-test/detectron2/projects/DensePoseFnL/densepose/modeling/geffnet_backbone.py", line 8, in <module>
    from geffnet import GenEfficientNet, set_exportable, set_scriptable, gen_efficientnet, mobilenetv3, efficientnet_builder
ModuleNotFoundError: No module named 'geffnet'

**Comment by zetyquickly** [comment]
Hello, glad to see you are interested in our project.

Regarding your problem I recommend comment this import or install geffnet via pip. This import is not used in the latest version. We use timm module as backbone

**Comment by abhaydoke09** [comment]
That solved the issue. Thanks
